In [5]:
#Python Data Types

#float - real numbers
#int - integer numbers
#str - string, text
#bool - True, False

print(type(1.42))
print(type(3))
print(type("hello"))
print(type(True))

<class 'float'>
<class 'int'>
<class 'str'>
<class 'bool'>


In [6]:
#List slicing
#[start:end]: start is inclusive but end is exclusive
l = [1,2,3,4,5,6]
l[0:3]

[1, 2, 3]

In [8]:
#List manipulation
#Change list in place
x = [1,2,3]
y = x
y[0] = 8
print(y)
print(x)
#Change list in a copy
a = [1,2,3]
b = list(a)
b[0] = 8
print(b)
print(a)

[8, 2, 3]
[8, 2, 3]
[8, 2, 3]
[1, 2, 3]


In [16]:
#Functions: Piece of reusable code; Solves particular task
#ROUND(number, ndigits) the ndigits argument can be negative? Yes!
round(3347,-1) #result: 3350
round(3347,-2) #result: 3300

#Methods: Functions that belong to objects. Objects have methods associated, depending on type.
#Objects can be str, float, list...(Everything)
str.capitalize()
str.replace()

float.bit_length()
float.conjugate()

list.index()
list.count()

#Summary
#1: Find out the object type
#2: Call functions/Use methods associated with this type of objects

3300

In [18]:
#Packages: Directory of Python Scripts
#Each script = module, specify functions, methods, types

#Numpy: Numeric Python
#Alternative to Python List: Numpy Array (contain only one type)
#Calculations over entire arrays
import numpy as np
height = [1.6,1.7,1.8]
np_height = np.array(height)
print(type(height))
print(type(np_height))

<class 'list'>
<class 'numpy.ndarray'>


In [20]:
#Different types: different behavior
a = [1,2,3] #List
b = np.array([1,2,3]) #Numpy Array
print(a + a)
print(b + b)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [45]:
#2D Numpy Arrays
np_2d = np.array([[1,2,3],[4,5,6]]) #List contains many lists
print(np_2d)
print(np_2d.shape)

#Subsetting
print(np_2d[0])

print(np_2d[0][1])
print(np_2d[0,1])

print(type(np_2d[0]))

print(type(np_2d[0][1]))
print(type(np_2d[0,1]))

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3]
2
2
<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [50]:
print(np.mean(np_2d[0,1]))
print(np.median(np_2d[0]))

print(np.corrcoef(np_2d[:,0],np_2d[:,1])) #np.corrcoef(): correlation coefficient
print(np.std(np_2d[:,1])) #standard deviation of the 2nd column
print(np.std(np_2d[1])) #standard deviation of the 2nd row

2.0
2.0
[[1. 1.]
 [1. 1.]]
1.5
0.816496580927726


In [53]:
#Generate data
#np.random.normal(distribution mean, distribution std, number of samples)
height = np.round(np.random.normal(1.75, 0.25, 2000), 2)
weight = np.round(np.random.normal(60.32, 15, 2000), 2)
np_body = np.column_stack((height,weight))
print(np_body)

[[ 1.84 62.06]
 [ 1.75 51.5 ]
 [ 2.41 42.39]
 ...
 [ 1.41 53.8 ]
 [ 1.81 64.4 ]
 [ 2.2  83.06]]
